Algoritmo "Ex01_Subtração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Gabriel
// Data atual  : 11/02/2023
Var
v1,v2,sub,resultado : inteiro

procedimento sub (a,b :inteiro)

Inicio

resultado <- a - b
fimprocedimento

Inicio
      escreva("Primeiro Valor: ")
       leia(v1)
      escreva("Segundo Valor: ")
       leia(v2)
       
       sub(v1,v2)
       
escreva(resultado)
Fimalgoritmo