Algoritmo "Ex03_Medias"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Gabriel
// Data atujl  : 11/02/2023
Var
// Seção de Declarações das variáveis 
i,j:inteiro
vNomes: vetor[1..2] de caractere
nome:caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 2 faca
     escreva("nome: ")
      leia(vNomes[i])
fimpara
      
para j de 1 ate 2 faca
       escreval(vNomes[j])
fimpara


Fimalgoritmo