Algoritmo "Notas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Gabriel
// Data atual  : 11/02/2023
Var
// Seção de Declarações das variáveis 
i :inteiro
nome :caractere
nota :real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 0
nota <- 0
para i de 1 ate 4 passo 1 faca

     escreval("Digite o nome: ")
      leia(nome)
     escreva("Sua nota: ")
      leia(nota)
      
fimpara

Fimalgoritmo